---
- name: Create configuration directory
  become: true
  file:
    path: "{{ config.path|default(config_dir) }}"
    state: directory
    owner: "{{ traefik_user }}"
    group: "{{ traefik_user }}"
  tags:
    - config

- name: Create configuration log directory
  become: true
  when: config.traefikLog.filePath is defined and config.traefikLog.filePath|length > 0
  file:
    path: "{{ config.traefikLog.filePath|dirname }}"
    state: directory
    owner: "{{ traefik_user }}"
    group: "{{ traefik_user }}"
  tags:
    - config

- name: Create configuration access log directory
  become: true
  when: config.accessLog.filePath is defined and config.accessLog.filePath|length > 0
  file:
    path: "{{ config.accessLog.filePath|dirname }}"
    state: directory
    owner: "{{ traefik_user }}"
    group: "{{ traefik_user }}"
  tags:
    - config

- name: Render configuration file
  become: true
  template:
    src: traefik.yml.j2
    dest: "{{ config.path|default(config_dir) }}/{{ config.name|default(_service_name) }}.yml"
    owner: "{{ traefik_user }}"
    group: "{{ traefik_user }}"
    mode: 0664
    backup: true
  vars:
    conf: "{{ config.config }}"
  tags:
    - config
